steps:
  - name: "gcr.io/cloud-builders/docker"
    args: 
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"
      - "--build-arg"
      - "BASE_URL=$_BASE_URL"
      - "--build-arg"
      - "CONTENT_URL=$_CONTENT_URL"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - $_RELEASE_NAME
      - kubernetes
      - --set
      - image.repository=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME
    env:
      - KUBECONFIG=/workspace/.kube/config
substitutions:
  _BASE_URL: http://localhost:3000/beprivatefund
  _CONTENT_URL: https://scontent.finnomena.com
  _CUSTOM_ZONE: asia-southeast1-a
  _CUSTOM_CLUSTER: kube01p
  _RELEASE_NAME: finno-privatefund-external-web
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]